language: java
os: linux
jobs:
    include:
        - os: linux
          dist: bionic
          jdk: openjdk11
          after_success:
              - mvn clean test jacoco:report coveralls:report

        - os: linux
          dist: xenial
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - gcc-6
                      - g++-6
                      - libstdc++6
          env: CC=gcc-6 CXX=g++-6
          jdk: openjdk8

        - os: osx
          osx_image: xcode10.2
    allow_failures:
        - dist: trusty

## Uncomment section below and the packages above to build unreleased snapshots of karmaresearch/vlog into vlog4j-base jar
before_install:
#    # explicitly avoid bash as travis screws with .bashrc,
#    # cf. https://travis-ci.community/t/travis-functions-no-such-file-or-directory/2286/12
#   - "[ -x /bin/dash ] && /bin/dash ./build-vlog-library.sh || /bin/sh ./build-vlog-library.sh"

install: mvn install $OPTIONS -DskipTests=true

cache:
  directories:
    - ./local_builds
    - $HOME/.m2
